set nocompatible

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Look and feel
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Source tree
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'

" Error checking
Plugin 'vim-syntastic/syntastic'

" Tagging/symbols
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'
Plugin 'majutsushi/tagbar'

" File search
" <C-p> to search, enter to open file or <C-t> to open in a new tab
Plugin 'ctrlpvim/ctrlp.vim'

" Automatically open corresponding header/source file with :AT
Plugin 'vim-scripts/a.vim'

" Git plugins
Plugin 'airblade/vim-gitgutter'
" Check out repository for aliases
Plugin 'tpope/vim-fugitive'

" Automatically create matching delimiters
Plugin 'Raimondi/delimitMate'

" Load man-pages with vim
" Plugin 'jez/vim-superman'

" tmux window switching
Plugin 'christoomey/vim-tmux-navigator'

" Syntax plugins
" None for now...add plugins if you need support for other languages

" Highlight and clear trailing whitespace
Plugin 'ntpeters/vim-better-whitespace'

" Make tmux look like vim-airline
Plugin 'edkolev/tmuxline.vim'

call vundle#end()

filetype plugin indent on

" General Settings
set backspace=indent,eol,start
set ruler
set number
set expandtab
set softtabstop=4
set tabstop=4
set shiftwidth=4
set autoindent
set number
set showcmd
set colorcolumn=80
set incsearch
set hlsearch

nnoremap <silent> <C-a> :nohl<CR><C-a>
inoremap ;l <Esc>`^

autocmd Filetype cpp setlocal softtabstop=2 tabstop=2 shiftwidth=2

set mouse=a

hi clear SignColumn

set t_Co=16
syntax on

" Plugin Settings

" altercation/vim-colors-solarized
" Set to "light" for light colorscheme
set background=dark

colorscheme solarized

" bling/vim-airline
" Always show status bar
set laststatus=2
" Fancy arrow symbols
let g:airline_powerline_fonts=1
" Show PASTE if in paste mode
let g:airline_detect_paste=1
" Show airline for tabs too
let g:airline#extensions#tabline#enabled=1
" Use solarized theme for status bar
let g:airline_theme='solarized'

" jistr/vim-nerdtree-labs
" Toggle NERDTree with \t
nmap <silent> <leader>t :NERDTreeTabsToggle<CR>
" Always have NERDTree open on startup
let g:nerdtree_tabs_open_on_console_startup=1

" scrooloose/syntastic
let g:syntastic_error_symbol='✘'
let g:syntastic_warning_symbol='▲'
augroup mySyntastic
    au!
    au FileType tex let b:syntastic_mode="passive"
augroup END

" xolox/vim-easytags
" Where to find tags
set tags=./tags;,~/.vimtags
" Defaults
let g:easytags_events=['BufReadPost', 'BufWritePost']
let g:easytags_async=1
let g:easytags_dynamic_files=2
let g:easytags_resolve_links=1
let g:easytags_supporess_ctags_warning=1

" majutsushi/tagbar
" Toggle tagbar with \b
nmap <silent> <leader>b :TagbarToggle<CR>
" Uncomment to open tagbar automatically whenever possible
"autocmd BufEnter * nested :call tagbar#autoopen(0)

" airbloade/vim-gitgutter
" In vim-airline, only display "hunks" if the diff is non-zero
let g:airline#extensions#hunks#non_zero_only=1

" Raimondi/delimitMate
let delimitMate_expand_Cr=1
augroup mydelimitMate
    au!
    au FileType markdown let b:delimitMate_nesting_quotes=["`"]
    au FileType tex let b:delimitMate_quotes=""
    au FileType tex let b:delimitMate_matchpairs="(:),[:],{:},`:'"
    au FileType python let b:delimitMate_nesting_quotes=['"',"'"]
augroup END

" ntpeters/vim-better-whitespace
" Strip whitespace on save
"autocmd BufEnter * EnableStripWhitespaceOnSave
" Strip whitespace with \-
nmap <silent> <leader>- :StripWhitespace<CR>
