version: "3"
services:
  app:
    container_name: server
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - MONGO_HOSTNAME=mongo
    volumes:
      - .:/app
  mongo:
    container_name: db
    image: mongo:4.0
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./dbdata:/data/db

